---
title: "injection_data_cleaning"
author: "Vikas Maturi"
date: 2022-03-01
output: 
  github_document:
    md_extension: +gfm_auto_identifiers
    toc: true
    toc_depth: 6
---



## Clean injection data

```{r, eval = FALSE} 

# for testing - do not evaluation

raw_injection %>% 
  filter(patient_guid == "000bb3881e3a40e28324582e5c8bfe1d") %>% 
  arrange(desc(injection_date))

all %>%
  filter(pt_code_name == "0019c0027b5e409b94c5870ae902737c") %>% 
  arrange(desc(index_date))
```


```{r, eval = FALSE}

# identify injections for patient/eye pairs in the study
in_study <-
  all %>% 
  mutate(
    eye1 = if_else(eye == 1, 1, 0),
    eye2 = if_else(eye == 2, 1, 0)
  )  %>%
  group_by(pt_code_name) %>% 
  summarize(eye1 = sum(eye1), eye2 = sum(eye2))

# for each patient/eye/injection date group, identify whether there is at least one injection entry marked in eye 1, eye 2, or eye 4 (not defined)
eye_match <-
  raw_injection %>% 
  # some people have multiple injections for the same eye on the same date listed - remove those injections
  select(patient_guid, eye, injection_date) %>%
  group_by(patient_guid, eye, injection_date) %>% 
  sample_n(1) %>% 
  group_by(patient_guid, injection_date) %>% 
  add_count(eye) %>% 
  ungroup() %>% 
  arrange(desc(n)) %>% 
  # for each patient/injection date, determine whether they are listed as receiving an injection in eye 1, 2, and/or 4
  spread(eye, n) %>% 
  rename(
    "one" = `1`, 
    "two" = `2`,
    "four" = `4`
  )


# flag each patient/eye/injection date grouping based on the 1/2/4 eye specification AND which patient/eyes pairs are in the dataset, if any
# injection data actions: https://docs.google.com/spreadsheets/d/1Sg7CWuF5Bp-p76gc5IliIxdquiZlx3KAkVvKiHGjWvE/edit#gid=0
injection_clean <-
  eye_match %>% 
  left_join(in_study, by = c("patient_guid" = "pt_code_name")) %>% 
  # join in index date, to calculate injections within the first year. 
  left_join(all %>% dplyr::select(pt_code_name, index_date), by = c("patient_guid" = "pt_code_name")) %>% 
  # calculate days past index date of injection
  mutate(
    days_past_first_injection = injection_date - index_date
  ) %>% 
  # only keep injection data in first year
  filter(days_past_first_injection > -1L, days_past_first_injection < 367) %>% 
  mutate(
    new_eye = case_when(
      (one == 1 & is.na(two) & is.na(four)) ~ 1, # keep entry
      (is.na(one) & two == 1 & is.na(four)) ~ 2,  # keep entry
      (is.na(one) & is.na(two) & four > 0 & eye1 == 1 & eye2 == 0) ~ 1, # reassign entry to eye 1
      (is.na(one) & is.na(two) & four > 0 & eye1 == 0 & eye2 == 1) ~ 2, # reassign entry to eye 2
      (is.na(one) & is.na(two) & four > 0 & eye1 == 1 & eye2 == 1) ~ 5, # remove pt. eye 1 and 2 from dataset
      (one == 1 & two == 1 & is.na(four)) ~ 3, # 3 means entries should be made for both eyes 
      (one == 1 & is.na(two) & four > 0 & eye1 == 1 & eye2 == 0) ~ 4, # keep entry (four will go away)
      (one == 1 & is.na(two) & four > 0 & eye1 == 0 & eye2 == 1) ~ 6, # keep entry (four will go away), remove pt. eye 2 data 
      (one == 1 & is.na(two) & four > 0 & eye1 == 1 & eye2 == 1) ~ 6, # keep entry (four will go away), remove pt. eye 2 data 
      (is.na(one) & two == 1 & four > 0 & eye1 == 0 & eye2 == 1) ~ 8, # keep entry (four will go away), remove pt. eye 1 data 
      (is.na(one) & two == 1 & four > 0 & eye1 == 1 & eye2 == 0) ~ 4, # keep entry (four will go away)
      (is.na(one) & two == 1 & four > 0 & eye1 == 1 & eye2 == 1) ~ 8, # keep entry (four will go away), remove pt. eye 1 data
      (one == 1 & two == 1 & four > 0 & eye1 == 1 & eye2 == 0) ~ 9, # keep entry (two and four will go away)
      (one == 1 & two == 1 & four > 0 & eye1 == 0 & eye2 == 1) ~ 9, # keep entry (one and four will go away)
      (one == 1 & two == 1 & four > 0 & eye1 == 1 & eye2 == 1) ~ 9, # keep entry (four will go away)
      TRUE ~ NA_real_
    )
  )

#write_csv(injection_clean, path = injection_clean_path)

```

```{r, eval = FALSE}

# read in the clean injection file, developed in the above code
injection_clean <- read_csv(injection_clean_file)

# identify pateints to remove based on classification above
pts_to_remove <-
  injection_clean %>% 
  group_by(patient_guid) %>% 
  # see the classification table on the explanation for why these codes merit different forms of removal
  mutate(
    # remove all patient data for the first eye
    remove1 = ifelse(any(new_eye == 8), 1, 0),
    # remove all patient data for the second eye
    remove2 = ifelse(any(new_eye == 6), 1, 0),
    # remove all patient data
    removeboth = ifelse(any(new_eye == 5), 1, 0),
  ) %>% 
  select(patient_guid, remove1, remove2, removeboth) %>% 
  sample_n(1)


pts_to_remove %>% 
  ungroup() %>% 
  count(remove1, remove2, removeboth)

# construct preliminary injection dataset
injections <-
  # again, remove duplicate entries to have just one patient/injection date/eye group
  raw_injection %>%
  select(patient_guid, eye, injection_date) %>% 
  group_by(patient_guid, eye, injection_date) %>% 
  sample_n(1) %>% 
  ungroup() %>% 
  # join in the "cleaned" dataset that provides updated codes for patients
  left_join(
    injection_clean %>% 
      select(patient_guid, injection_date, new_eye) %>% 
      group_by(patient_guid, injection_date, new_eye) %>% 
      sample_n(1), 
    by = c("patient_guid", "injection_date")) %>% 
  # based on codes above, manipulate the data
  mutate(
    eye = ifelse(new_eye == 1 & eye == 4, 1, eye),
    eye = ifelse(new_eye == 2 & eye == 4, 2, eye),
  ) %>% 
  # remove patients identified as "to be removed" based on the classification
  left_join(pts_to_remove, by = "patient_guid") %>% 
  filter(
    !(eye == 1 & remove1 == 1),
    !(eye == 2 & remove2 == 1), 
    !(removeboth == 1)
  )  %>% 
  left_join(all %>% dplyr::select(pt_code_name, index_date, eye), by = c("patient_guid" = "pt_code_name", "eye")) %>% 
  # calculate days past index date of injection
  mutate(
    days_past_first_injection = injection_date - index_date
  ) %>% 
  # only keep injection data in first year
  filter(days_past_first_injection > -1L, days_past_first_injection < 367)

test <-
  # again, remove duplicate entries to have just one patient/injection date/eye group
  raw_injection %>%
  select(patient_guid, eye, injection_date) %>% 
  group_by(patient_guid, eye, injection_date) %>% 
  sample_n(1) %>% 
  ungroup() %>% 
  # join in the "cleaned" dataset that provides updated codes for patients
  left_join(
    injection_clean %>% 
      select(patient_guid, injection_date, new_eye) %>% 
      group_by(patient_guid, injection_date, new_eye) %>% 
      sample_n(1), 
    by = c("patient_guid", "injection_date")) %>% 
  # based on codes above, manipulate the data
  mutate(
    eye = ifelse(new_eye == 1 & eye == 4, 1, eye),
    eye = ifelse(new_eye == 2 & eye == 4, 2, eye),
  ) %>% 
  # remove patients identified as "to be removed" based on the classification
  left_join(pts_to_remove, by = "patient_guid") %>% 
  filter(
    !(eye == 1 & remove1 == 1),
    !(eye == 2 & remove2 == 1), 
    !(removeboth == 1)
  )  %>% 
  left_join(all %>% dplyr::select(pt_code_name, index_date, eye), by = c("patient_guid" = "pt_code_name", "eye")) %>% 
  # calculate days past index date of injection
  mutate(
    days_past_first_injection = injection_date - index_date
  ) 
  
# identify patients to remove that have injections too close together (implying incorrect data)
injections_remove <-
  injections %>% 
  group_by(patient_guid, eye) %>% 
  arrange(injection_date) %>% 
  mutate(prior_date = lag(injection_date)) %>% 
  mutate(
    too_close = ifelse(!is.na(prior_date), ifelse(injection_date - prior_date < 22, 1, 0), 0)
  ) %>% 
  mutate(remove_close = ifelse(any(too_close == 1), 1, 0)) %>% 
  ungroup() %>% 
  select(patient_guid, eye, remove_close) %>% 
  group_by(patient_guid, eye, remove_close) %>% 
  sample_n(1) %>% 
  ungroup()

# remove patients with injections too close together (identified above)
injections2 <-
  injections %>% 
  left_join(injections_remove, by = c("patient_guid", "eye")) %>% 
  filter(remove_close == 0)

# identify patients where the first injection is more than 60 days after the index date. 
inj_rem_date <-
  injections2 %>% 
  group_by(patient_guid, eye) %>%
  arrange(injection_date) %>% 
  mutate(first_entry = ifelse(row_number() == 1, 1, 0)) %>%
  ungroup() %>% 
  mutate(
    inj_index_diff = injection_date - index_date,
    gap = ifelse(inj_index_diff > 180, 1, 0),
    gap_first = ifelse(gap == 1 & first_entry == 1, 1, 0)
  ) %>% 
  group_by(patient_guid, eye) %>%
  mutate(remove_gap = if_else(any(gap_first == 1), 1, 0)) %>% 
  ungroup() %>% 
  select(patient_guid, eye, remove_gap) %>% 
  group_by(patient_guid, eye, remove_gap) %>% 
  sample_n(1) %>% 
  ungroup()

# remove patients where the first injection is more than 60 days after the index date
# when this is the case, it suggests that the index date might be wrong 
injections3 <-
  injections2 %>% 
  left_join(inj_rem_date, by = c("patient_guid", "eye")) %>% 
  filter(remove_gap == 0)
```


```{r, eval = FALSE}

# for each patient, number of injections in first year
inj_per_patient3 <-
  all %>% 
  left_join(injections3 %>% select(patient_guid, eye, injection_date), by = c("pt_code_name" = "patient_guid", "eye")) %>% 
  count(pt_code_name, eye) %>% 
  arrange(desc(n))

# count of patients that had each number of injections in one year
count_inj_per_year <-
  inj_per_patient3 %>% 
  count(n)

count_inj_per_year

# plotting histogram of above data
inj_per_patient3 %>% 
  ggplot(aes(x = n)) +
  geom_histogram(binwidth = 1) +
  theme_light() + 
  labs(
    title = "Total number of patients that received the number of injections in one year", 
    x = "Number of injections within one year of index date", 
    y = "Count"
  )

```
